// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krqhhjkdvgddaghkxwdg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtycWhoamtkdmdkZGFnaGt4d2RnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2ODk2ODYsImV4cCI6MjA2MTI2NTY4Nn0.neWw9AgO9An4eu4nnzylgmtoulLSyubbI0ytcLixV7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});